apiVersion: v1
kind: Service
metadata:
  name: ship-service
  namespace: rso
spec:
  selector:
    app: ship-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-service
  namespace: rso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship-service
  template:
    metadata:
      labels:
        app: ship-service
    spec:
      containers:
        - name: ship-service
          image: ship-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/appdb
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "pass"
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 5

